export const HEADER_HEIGHT = 50;
export const FOOTER_HEIGHT = 100;
export const IS_DRAGGABLE = true;

export const POSITION_FIXED = [
  {
    x: 'left',
    y: 'top',
    contentX: 'start',
    contentY: 'start',
    position: 'fixed',
    offsetX: 10,
    offsetY: 10,
  },
  {
    x: 'center',
    y: 'top',
    contentX: 'middle',
    contentY: 'start',
    position: 'fixed',
  },
  {
    x: 'right',
    y: 'top',
    contentX: 'end',
    contentY: 'start',
    position: 'fixed',
  },
  {
    x: 'left',
    y: 'center',
    contentX: 'start',
    contentY: 'middle',
    position: 'fixed',
  },
  {
    x: 'center',
    y: 'center',
    contentX: 'middle',
    contentY: 'middle',
    position: 'fixed',
  },
  {
    x: 'right',
    y: 'center',
    contentX: 'end',
    contentY: 'middle',
    position: 'fixed',
  },
  {
    x: 'left',
    y: 'bottom',
    contentX: 'start',
    contentY: 'end',
    position: 'fixed',
  },
  {
    x: 'center',
    y: 'bottom',
    contentX: 'middle',
    contentY: 'end',
    position: 'fixed',
  },
  {
    x: 'right',
    y: 'bottom',
    contentX: 'end',
    contentY: 'end',
    position: 'fixed',
  },
];
export const POSITION_RELATIVE = [
  {
    x: 'left',
    y: 'top',
    contentX: 'start',
    contentY: 'start',
    position: 'relative',
    offsetX: 10,
    offsetY: 10,
  },
  {
    x: 'center',
    y: 'top',
    contentX: 'middle',
    contentY: 'start',
    position: 'relative',
  },
  {
    x: 'right',
    y: 'top',
    contentX: 'end',
    contentY: 'start',
    position: 'relative',
  },
  {
    x: 'left',
    y: 'center',
    contentX: 'start',
    contentY: 'middle',
    position: 'relative',
  },
  {
    x: 'center',
    y: 'center',
    contentX: 'middle',
    contentY: 'middle',
    position: 'relative',
  },
  {
    x: 'right',
    y: 'center',
    contentX: 'end',
    contentY: 'middle',
    position: 'relative',
  },
  {
    x: 'left',
    y: 'bottom',
    contentX: 'start',
    contentY: 'end',
    position: 'relative',
  },
  {
    x: 'center',
    y: 'bottom',
    contentX: 'middle',
    contentY: 'end',
    position: 'relative',
  },
  {
    x: 'right',
    y: 'bottom',
    contentX: 'end',
    contentY: 'end',
    position: 'relative',
  },
];
